---
version: "3.7"
services:
  airflow:
    environment:
      - BACKEND=sqlite
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${SQLITE_URL}
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
    volumes:
      - /dev/urandom:/dev/random   # Required to get non-blocking entropy source
      - sqlite-db-volume:/root/airflow
volumes:
  sqlite-db-volume: