---
version: "3.7"
services:
  airflow:
    image: ghcr.io/apache/airflow/main/ci/python3.7
    env_file: devcontainer.env
    ports:
      - "22:22"
      - "8080:8080"
      - "5555:5555"
      - "6379:6379"
    cap_add:
      - SYS_PTRACE
    volumes:
      # Pass docker to inside of the container so that Kind and Moto tests can use it.
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/urandom:/dev/random   # Required to get non-blocking entropy source